version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn run start:dev --debug 0.0.0.0:9229
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: arbitrage-bot-api
    ports:
      - 27017:27017
    volumes:
      - '/var/docker/mongodb/arbitrage-bot-api/data:/data/db'
  mongoclient:
    image: mongoclient/mongoclient:latest
    ports:
      - 3300:3000
    depends_on:
      - mongodb
